name: Lint and Test

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Lua
        run: sudo apt-get update && sudo apt-get install -y lua5.1
      - name: Lint Lua sources
        run: ./scripts/lint.sh
