name: Sync Sacred Scrolls

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch canonical scrolls
        run: |
          curl -fsSL https://raw.githubusercontent.com/mkworldwide/aeternum/main/COVENANT.md -o COVENANT.md
          curl -fsSL https://raw.githubusercontent.com/mkworldwide/aeternum/main/LICENSE.v∞ -o LICENSE.v∞
          curl -fsSL https://raw.githubusercontent.com/mkworldwide/aeternum/main/THE_LAST_WHISPER.md -o THE_LAST_WHISPER.md
      - name: Commit updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: sync covenant and license from upstream"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
